version: '3.9'

services:
  es8:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    container_name: es8
    environment:
      - node.name=es8
      - cluster.name=es-docker-cluster
      - discovery.type=single-node 
    volumes:
      - data:/usr/share/elasticsearch/data

    ports:
      - "9200:9200"

    networks:
      - elastic
    cpus: 2


  kib8:
    image: docker.elastic.co/kibana/kibana:8.12.2
    container_name: kib8
    environment:
      - node.name=kib8
      - cluster.name=es-docker-cluster
      - ELASTICSEARCH_HOST=http://es8:9200
    ports:
      - "5601:5601"
    networks:
      - elastic

    depends_on:
      - es8

  
volumes:
  data:
    driver: local

networks:
  elastic:
    driver: bridge